In [16]:
import numpy as np

In [17]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])

In [18]:
a

array([1, 2, 3])

In [19]:
b

array([[1],
       [2],
       [3]])

In [20]:
a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

Rank 1 array

In [22]:
a = np.random.randn(5)
a

array([-0.12505613,  0.45269053,  1.57132598,  1.40896701,  0.59310056])

In [23]:
a.shape

(5,)

Here we can see that the shape is (5,) its not a row vector or col vector, it is called rank vector. Normally we avoid rank vectors in ML, for avoid broadcasting errors

Row Vector(one row and multiple cols)

In [25]:
row_vector = np.random.randn(1,5)
row_vector

array([[-0.58989979,  0.60237523,  0.59198898,  0.7584113 , -0.12364254]])

In [26]:
row_vector.shape

(1, 5)

Column Vector(one col and mulitple rows)

In [27]:
col_vector = np.random.randn(5,1)
col_vector

array([[ 0.58919329],
       [-0.82154493],
       [ 0.55320972],
       [-0.17045756],
       [ 1.71996809]])

In [28]:
col_vector.shape

(5, 1)