# **Anomoly Detection**

In [1]:
from tensorflow.keras.layers import Dense,Activation,BatchNormalization,Dropout,Input

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
input_size = (100000,10)

In [4]:
normal_data = np.random.normal(loc=5,scale=1,size=input_size)
normal_data.shape

(100000, 10)

In [5]:
normal_data

array([[3.74136209, 7.69830715, 3.17007539, ..., 3.38794026, 5.35454288,
        3.22605588],
       [4.44048279, 4.16330226, 4.25365855, ..., 3.65102234, 5.47188743,
        4.53383669],
       [4.819485  , 4.42485722, 4.62389346, ..., 4.86573521, 4.52295622,
        5.85669411],
       ...,
       [6.90008238, 6.24728665, 4.80241231, ..., 6.22516508, 4.53676522,
        5.22495911],
       [5.17232201, 4.03859467, 6.62282542, ..., 4.96407494, 4.7271801 ,
        4.94416075],
       [4.35580171, 5.88023736, 4.05040673, ..., 4.35185214, 3.48851117,
        6.7629832 ]])

In [6]:
normalize_data = (normal_data - np.min(normal_data)) / (np.max(normal_data) - np.min(normal_data))

In [7]:
autoencoder = tf.keras.Sequential([
    Input(shape=(input_size[1],)),
    BatchNormalization(),
    Dense(units=64),
    BatchNormalization(),
    Activation('relu'),
    Dropout(0.2),
    Dense(units=32),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=16),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=input_size[1],),
    Activation('sigmoid')
])

In [8]:
autoencoder.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [ ]:
autoencoder.fit(normalize_data,normalize_data,epochs=20,batch_size=32,validation_split=0.2)

Epoch 1/20


In [89]:
np.array([100,200,300])

array([100, 200, 300])

In [92]:
abnormal_data = np.array([[100,200,300,500,60,90,0,99,100,209]])

In [ ]:
normalize_abnormal_data = (abnormal_data - np.min(abnormal_data)) / np.max(abnormal_data) - np.min(abnormal_data) 

In [96]:
normalize_abnormal_data

array([[0.2  , 0.4  , 0.6  , 1.   , 0.12 , 0.18 , 0.   , 0.198, 0.2  ,
        0.418]])

In [ ]:
autoencoder.predict(normalize_abnormal_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


array([[1.        , 0.99999994, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]],
      dtype=float32)