# **Anomoly Detection**

In [1]:
from tensorflow.keras.layers import Dense,Activation,BatchNormalization,Dropout,Input

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
input_size = (100000,10)

In [4]:
normal_data = np.random.normal(loc=5,scale=1,size=input_size)
normal_data.shape

(100000, 10)

In [5]:
normal_data

array([[3.74136209, 7.69830715, 3.17007539, ..., 3.38794026, 5.35454288,
        3.22605588],
       [4.44048279, 4.16330226, 4.25365855, ..., 3.65102234, 5.47188743,
        4.53383669],
       [4.819485  , 4.42485722, 4.62389346, ..., 4.86573521, 4.52295622,
        5.85669411],
       ...,
       [6.90008238, 6.24728665, 4.80241231, ..., 6.22516508, 4.53676522,
        5.22495911],
       [5.17232201, 4.03859467, 6.62282542, ..., 4.96407494, 4.7271801 ,
        4.94416075],
       [4.35580171, 5.88023736, 4.05040673, ..., 4.35185214, 3.48851117,
        6.7629832 ]])

In [6]:
normalize_data = (normal_data - np.min(normal_data)) / (np.max(normal_data) - np.min(normal_data))

In [7]:
autoencoder = tf.keras.Sequential([
    Input(shape=(input_size[1],)),
    BatchNormalization(),
    Dense(units=64),
    BatchNormalization(),
    Activation('relu'),
    Dropout(0.2),
    Dense(units=32),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=16),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=input_size[1],),
    Activation('sigmoid')
])

In [8]:
autoencoder.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [9]:
autoencoder.fit(normalize_data,normalize_data,epochs=20,batch_size=32,validation_split=0.2)

Epoch 1/20


2500/2500 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.0081 - mse: 0.0081 - val_loss: 6.5319e-04 - val_mse: 6.5319e-04
Epoch 2/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0019 - mse: 0.0019 - val_loss: 3.5082e-04 - val_mse: 3.5082e-04
Epoch 3/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.0016 - mse: 0.0016 - val_loss: 2.5231e-04 - val_mse: 2.5231e-04
Epoch 4/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0014 - mse: 0.0014 - val_loss: 2.1171e-04 - val_mse: 2.1171e-04
Epoch 5/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0014 - mse: 0.0014 - val_loss: 2.0332e-04 - val_mse: 2.0332e-04
Epoch 6/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0013 - mse: 0.0013 - val_loss: 1.6985e-04 - val_mse: 1.6985e-04
Epoch 7/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 1.7085e-04 - val_mse: 1.7085e-04
Epoch 8/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 1.5615e-04 - val_mse

In [10]:
np.array([100,200,300])

array([100, 200, 300])

In [36]:
abnormal_data = np.array([[10,270,30,50,60,90,0,99,10,29]])

In [37]:
normalize_abnormal_data = (abnormal_data - np.min(abnormal_data)) / np.max(abnormal_data) - np.min(abnormal_data) 

In [38]:
normalize_abnormal_data

array([[0.03703704, 1.        , 0.11111111, 0.18518519, 0.22222222,
        0.33333333, 0.        , 0.36666667, 0.03703704, 0.10740741]])

In [39]:
normalize_data[0]

array([0.3773375 , 0.79861015, 0.31651597, 0.58499088, 0.29320715,
       0.3823351 , 0.36429387, 0.33971076, 0.54908336, 0.32247588])

In [40]:
test_normal = autoencoder.predict(np.array([normalize_data[1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


In [41]:
test_anomoly = autoencoder.predict(normalize_abnormal_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


In [42]:
np.sum(abs(test_normal - np.array([normalize_data[1]])))

0.08043476459151983

In [43]:
np.sum(abs(test_anomoly - normalize_abnormal_data))

0.918688914179802