# **Anomoly Detection**

In [4]:
from tensorflow.keras.layers import Dense,Activation,BatchNormalization,Dropout,Input

In [5]:
import numpy as np
import tensorflow as tf

In [6]:
input_size = (100000,10)

In [7]:
normal_data = np.random.normal(loc=5,scale=1,size=input_size)
normal_data.shape

(100000, 10)

In [8]:
normal_data

array([[5.54337051, 6.3469312 , 4.9438631 , ..., 5.26548713, 6.08531053,
        6.22775015],
       [6.9806034 , 5.08333195, 4.29184791, ..., 5.4147952 , 4.32804484,
        4.20710658],
       [6.22894644, 5.18967361, 4.93115398, ..., 4.37046312, 4.58870691,
        7.10828277],
       ...,
       [4.97869324, 5.75636611, 5.10197625, ..., 6.12917943, 5.0248943 ,
        4.83922852],
       [7.27303456, 4.13334973, 4.14679899, ..., 5.68908296, 5.24894594,
        5.75696688],
       [4.03059965, 5.7458108 , 6.1992113 , ..., 5.95429419, 5.47273061,
        4.94741252]])

In [9]:
normalize_data = (normal_data - np.min(normal_data)) / (np.max(normal_data) - np.min(normal_data))

In [10]:
autoencoder = tf.keras.Sequential([
    Input(shape=(input_size[1],)),
    BatchNormalization(),
    Dense(units=64),
    BatchNormalization(),
    Activation('relu'),
    Dropout(0.2),
    Dense(units=32),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=16),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=input_size[1],),
    Activation('sigmoid')
])

In [11]:
autoencoder.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [12]:
autoencoder.fit(normalize_data,normalize_data,epochs=20,batch_size=32,validation_split=0.2)

Epoch 1/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0070 - mse: 0.0070 - val_loss: 5.7632e-04 - val_mse: 5.7632e-04
Epoch 2/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.0016 - mse: 0.0016 - val_loss: 2.9017e-04 - val_mse: 2.9017e-04
Epoch 3/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.0014 - mse: 0.0014 - val_loss: 2.2041e-04 - val_mse: 2.2041e-04
Epoch 4/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 0.0013 - mse: 0.0013 - val_loss: 1.9890e-04 - val_mse: 1.9890e-04
Epoch 5/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 2.0533e-04 - val_mse: 2.0533e-04
Epoch 6/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 1.7670e-04 - val_mse: 1.7670e-04
Epoch 7/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.0011 - mse: 0.0011 - val_loss: 1.6172e-04 - val_mse: 1.6172e-04
Epoch 8/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.0011 - mse: 0.0011 - val_loss: 1.5765e-0

In [13]:
np.array([100,200,300])

array([100, 200, 300])

In [14]:
abnormal_data = np.array([[10,270,30,50,60,90,0,99,10,29]])

In [15]:
normalize_abnormal_data = (abnormal_data - np.min(abnormal_data)) / np.max(abnormal_data) - np.min(abnormal_data) 

In [16]:
normalize_abnormal_data

array([[0.03703704, 1.        , 0.11111111, 0.18518519, 0.22222222,
        0.33333333, 0.        , 0.36666667, 0.03703704, 0.10740741]])

In [17]:
normalize_data[0]

array([0.53342323, 0.61265492, 0.47431135, 0.49260664, 0.53714109,
       0.57959974, 0.62496402, 0.50602372, 0.58685893, 0.60090358])

In [18]:
test_normal = autoencoder.predict(np.array([normalize_data[1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step


In [19]:
test_anomoly = autoencoder.predict(normalize_abnormal_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


In [20]:
np.sum(abs(test_normal - np.array([normalize_data[1]])))

0.06585346113152224

In [21]:
np.sum(abs(test_anomoly - normalize_abnormal_data))

0.8950856188933056