In [140]:
import tensorflow as tf

FeedForward Neural network

In [141]:
data = tf.keras.datasets.boston_housing

In [142]:
(train_data, train_price), (test_data, test_price) = data.load_data()

In [143]:
train_data

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [144]:
train_price

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [145]:
input_size = train_data.shape[1]

In [146]:
normalization_layer = tf.keras.layers.Normalization()
normalization_layer.adapt(train_data)

In [147]:
learning_rate_scheduler = tf.keras.optimizers.schedules.ExponentialDecay(
    0.01,
    decay_steps=100000,
    decay_rate=0.96,
    staircase=True
)

In [148]:
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate_scheduler)

In [149]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(input_size,)),
    normalization_layer,
    tf.keras.layers.Dense(
        units=64, kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.Activation('relu'),
    tf.keras.layers.Dense(
        units=32, kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.Activation('relu'),
    tf.keras.layers.Dense(units=1)
])
model.compile(optimizer=optimizer, loss='mean_squared_error',
              metrics=['mean_absolute_error'])

In [150]:
model.fit(train_data, train_price, epochs=20, batch_size=32)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 432.3747 - mean_absolute_error: 18.6048
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90.3948 - mean_absolute_error: 7.5554  
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33.1383 - mean_absolute_error: 4.2553 
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.3485 - mean_absolute_error: 4.0330 
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.5410 - mean_absolute_error: 3.0714
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.0193 - mean_absolute_error: 2.6330 
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.1480 - mean_absolute_error: 2.5112  
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14.9317 - mean_absolute_error: 2.7487 
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.5810 - mean_absolute_error: 2.2575 
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.7463 - mean_absolute_error: 2.3007 
Epoch 11/20
13/13 ━━━━━━━━━━━

In [151]:
import numpy as np

In [152]:
np.mean(test_price)

23.07843137254902

In [ ]:
model.evaluate(test_data, test_price)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.1643 - mean_absolute_error: 2.6830  


[21.515317916870117, 2.9036946296691895]

In [154]:
pred = model.predict(test_data)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


In [155]:
test_price = np.reshape(test_price, (102, 1))

In [156]:
test_price.shape

(102, 1)

In [157]:
pred.shape

(102, 1)

In [158]:
test_price - pred

array([[ -0.95557194],
       [  1.1485775 ],
       [ -2.94163704],
       [ -6.62578964],
       [ -3.8489502 ],
       [  6.3827877 ],
       [  5.01233025],
       [  0.64726486],
       [  1.32837105],
       [  2.28593941],
       [  1.27392159],
       [ -1.59349632],
       [  2.15813236],
       [  9.12255096],
       [  2.91814308],
       [  3.83098869],
       [ -2.73361092],
       [ -0.04548378],
       [  1.89763985],
       [ -3.21059875],
       [  1.3759594 ],
       [ -4.11828213],
       [ -0.88586426],
       [  1.42324638],
       [ -0.91023598],
       [ -1.33941078],
       [ -2.20840645],
       [  0.50237999],
       [ -0.42323589],
       [  0.35156822],
       [  2.97553368],
       [  0.32399807],
       [ -1.42968216],
       [ -1.83219109],
       [  3.93594513],
       [ -0.7833992 ],
       [  0.37605133],
       [  6.34486275],
       [  0.86784515],
       [ -1.78954887],
       [  4.28736687],
       [  0.39925041],
       [  1.67306004],
       [  5

In [106]:
pred

array([[ 7.045989 ],
       [16.46475  ],
       [21.947647 ],
       [33.35642  ],
       [25.11064  ],
       [18.286001 ],
       [26.873854 ],
       [22.441221 ],
       [18.405218 ],
       [20.77057  ],
       [13.37509  ],
       [16.17318  ],
       [14.804958 ],
       [41.30829  ],
       [17.77972  ],
       [19.082815 ],
       [27.1878   ],
       [19.537497 ],
       [17.764942 ],
       [25.752768 ],
       [ 9.62147  ],
       [13.349571 ],
       [20.491087 ],
       [14.493345 ],
       [19.507254 ],
       [24.422148 ],
       [28.487823 ],
       [28.245283 ],
       [ 8.784103 ],
       [21.00677  ],
       [18.48473  ],
       [12.295208 ],
       [32.86241  ],
       [25.241182 ],
       [15.901819 ],
       [ 6.7315583],
       [13.927881 ],
       [16.10714  ],
       [18.909016 ],
       [25.97333  ],
       [29.38717  ],
       [28.026665 ],
       [12.820969 ],
       [41.553272 ],
       [30.742863 ],
       [24.58688  ],
       [26.91041  ],
       [15.70

CNN

In [159]:
(train_data, train_labels), (test_data,
                             test_labels) = tf.keras.datasets.mnist.load_data()

In [160]:
train_data.shape

(60000, 28, 28)

In [161]:
data_aug = tf.keras.Sequential([
    tf.keras.layers.Input((28, 28, 1)),
    tf.keras.layers.Rescaling(1./255),
    tf.keras.layers.RandomRotation(0.2),
    tf.keras.layers.RandomFlip('horizondal'),
    tf.keras.layers.RandomZoom(0.2, fill_mode='nearest'),
    tf.keras.layers.RandomTranslation(0.2, 0.2, fill_mode='nearest'),

])

In [162]:
cnn = tf.keras.Sequential([
    data_aug,
    tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=train_data.shape[1], activation='softmax')
])

In [163]:
cnn.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [164]:
cnn.fit(train_data, train_labels, epochs=10, batch_size=32)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.1684 - loss: 2.2694
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.3590 - loss: 1.7587
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 10ms/step - accuracy: 0.4213 - loss: 1.5961
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - accuracy: 0.5391 - loss: 1.3174
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 10ms/step - accuracy: 0.5965 - loss: 1.1646
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - accuracy: 0.6593 - loss: 1.0176
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 10ms/step - accuracy: 0.6958 - loss: 0.9094
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.7289 - loss: 0.8119
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - accuracy: 0.7520 - loss: 0.7404
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 8ms/step - accuracy: 0.7785 - loss: 0.6705


Neural Nets from scratch

In [169]:
def sigmoid(x):
    return 1/np.exp(-x)


def sigmoid_derivative(x):
    x = sigmoid(x)
    return x - (1-x)


def initialize_weights(input_size, hidden_size, output_size):
    W1 = np.random.randn(input_size, hidden_size),
    b1 = np.random.randn(1, hidden_size),
    W2 = np.random.randn(hidden_size, output_size)
    b2 = np.random.randn(1, output_size)
    return W1, b1, W2, b2