In [75]:
import tensorflow as tf

FeedForward Neural network

In [76]:
data = tf.keras.datasets.boston_housing

In [77]:
(train_data,train_price),(test_data,test_price) = data.load_data()

In [78]:
train_data

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [79]:
train_price

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [80]:
input_size = train_data.shape[1]

In [81]:
normalization_layer = tf.keras.layers.Normalization()
normalization_layer.adapt(train_data)

In [95]:
learning_rate_scheduler = tf.keras.optimizers.schedules.ExponentialDecay(
    0.01,
    decay_steps=100000,
    decay_rate=0.96,
    staircase=True
    )

In [96]:
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate_scheduler)

In [97]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(input_size,)),
    normalization_layer,
    tf.keras.layers.Dense(units=64,kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.Activation('relu'),
    tf.keras.layers.Dense(units=32,kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.Activation('relu'),
    tf.keras.layers.Dense(units=1)
])
model.compile(optimizer=optimizer,loss='mean_squared_error',metrics=['mean_absolute_error'])

In [98]:
model.fit(train_data,train_price,epochs=20,batch_size=32)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 480.5882 - mean_absolute_error: 19.9013   
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 101.2130 - mean_absolute_error: 7.7515 
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32.0973 - mean_absolute_error: 4.2305 
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.5055 - mean_absolute_error: 3.5561 
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.5713 - mean_absolute_error: 3.0036 
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14.3769 - mean_absolute_error: 2.5279
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.2376 - mean_absolute_error: 2.4473 
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.5162 - mean_absolute_error: 2.3168
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.2306 - mean_absolute_error: 2.3518
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1818 - mean_absolute_error: 2.4390 
Epoch 11/20
13/13 ━━━━━━━━━

In [101]:
import numpy as np

In [103]:
np.mean(test_price)

23.07843137254902

In [99]:
model.evaluate(test_data,test_price)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17.0132 - mean_absolute_error: 2.8621  


[21.753652572631836, 3.028883457183838]

In [105]:
pred = model.predict(test_data)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [115]:
test_price = np.reshape(test_price,(102,1))

In [116]:
test_price.shape

(102, 1)

In [111]:
pred.shape

(102, 1)

In [117]:
test_price - pred

array([[ 1.54010963e-01],
       [ 2.33524971e+00],
       [-2.94764709e+00],
       [-6.35641861e+00],
       [-2.91063957e+00],
       [ 6.21399879e+00],
       [ 4.32614632e+00],
       [ 4.58778763e-01],
       [ 2.09478188e+00],
       [ 2.42942924e+00],
       [ 5.22491035e+00],
       [-1.67317963e+00],
       [ 2.99504166e+00],
       [ 8.69171143e+00],
       [ 3.02027969e+00],
       [ 5.21718483e+00],
       [-2.98779945e+00],
       [ 2.62503433e-01],
       [ 1.33505783e+00],
       [-3.05276756e+00],
       [ 2.37852955e+00],
       [-3.14957123e+00],
       [-4.91086960e-01],
       [ 4.00665474e+00],
       [ 1.39274635e+00],
       [-1.42214775e+00],
       [-9.87823486e-01],
       [ 1.85471687e+00],
       [ 7.15896606e-01],
       [ 9.93230820e-01],
       [ 2.71527023e+00],
       [ 1.80479202e+00],
       [ 2.37588501e-01],
       [-1.84118233e+00],
       [ 4.19818077e+00],
       [ 6.68441677e-01],
       [ 1.47211876e+00],
       [ 7.69286041e+00],
       [ 1.1

In [106]:
pred

array([[ 7.045989 ],
       [16.46475  ],
       [21.947647 ],
       [33.35642  ],
       [25.11064  ],
       [18.286001 ],
       [26.873854 ],
       [22.441221 ],
       [18.405218 ],
       [20.77057  ],
       [13.37509  ],
       [16.17318  ],
       [14.804958 ],
       [41.30829  ],
       [17.77972  ],
       [19.082815 ],
       [27.1878   ],
       [19.537497 ],
       [17.764942 ],
       [25.752768 ],
       [ 9.62147  ],
       [13.349571 ],
       [20.491087 ],
       [14.493345 ],
       [19.507254 ],
       [24.422148 ],
       [28.487823 ],
       [28.245283 ],
       [ 8.784103 ],
       [21.00677  ],
       [18.48473  ],
       [12.295208 ],
       [32.86241  ],
       [25.241182 ],
       [15.901819 ],
       [ 6.7315583],
       [13.927881 ],
       [16.10714  ],
       [18.909016 ],
       [25.97333  ],
       [29.38717  ],
       [28.026665 ],
       [12.820969 ],
       [41.553272 ],
       [30.742863 ],
       [24.58688  ],
       [26.91041  ],
       [15.70

CNN