# **KNN**

## Theory

## Implementation

* Store datapoints
* calculate euclidean  distance of all datapoint from the target
* sort it and take the nearest k points
* Find the mode of their class
* Assign that class to the target

In [602]:
import numpy as np
from scipy import stats

In [603]:
x = np.array([[1,2],[3,4]])
y = np.array([5,6])
l = [0,1]
s = np.sum((x - y)**2,axis=1)
s = np.array(s)

In [604]:
a = np.array(sorted(enumerate(s),key=lambda x : x[1]))

In [605]:
a[:,0]

array([1, 0])

In [606]:
class KNN:
    def __init__(self, k=5):
        self.k = k
        self.features = []
        self.target = []
        self.distance = []

    def fit(self, x, y):
        self.features = np.array(x)
        self.target = y

    def predict(self, data):
        data = np.array(data)
        data = data[:,np.newaxis,:]
        self.features = self.features[np.newaxis,:,:]
        self.distance = np.sum((data - self.features)**2, axis=1)
        print(self.distance.shape)
        idx = np.argsort(self.distance)[:self.k]
        selected_target = self.target[idx]
        return stats.mode(selected_target, keepdims=False)[0]

In [607]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [608]:
X,y = make_classification(n_samples=1000,n_features=6,n_classes=2,random_state=42)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [609]:
X_test.shape

(200, 6)

In [610]:
knn = KNN()
knn.fit(X_train,y_train)

In [611]:
knn.predict(X_test)

(200, 6)


array([1, 1, 1, 1, 0, 0])

In [612]:
x = np.array([1,2,4,5,6,7,3,5,6])
x

array([1, 2, 4, 5, 6, 7, 3, 5, 6])

In [613]:
i = np.array([0,3])
i

array([0, 3])

In [614]:
x[i]

array([1, 5])

In [615]:
arr1 = np.random.rand(100, 3)  # Shape (100, 3)
arr2 = np.random.rand(50, 3)   # Shape (50, 3)

# Compute the differences using broadcasting
diff = arr2[:, np.newaxis, :] - arr1[np.newaxis, :, :]

In [616]:
diff.shape

(50, 100, 3)

In [617]:
arr = np.array([[1,2,4,5],[5,6,8,0],[1,6,7,8]])
arr

array([[1, 2, 4, 5],
       [5, 6, 8, 0],
       [1, 6, 7, 8]])

In [618]:
arr[:,np.newaxis,:]

array([[[1, 2, 4, 5]],

       [[5, 6, 8, 0]],

       [[1, 6, 7, 8]]])

In [619]:
arr2[:, np.newaxis, :]

array([[[0.21849729, 0.8147488 , 0.59932834]],

       [[0.90628231, 0.34832024, 0.32275225]],

       [[0.67517326, 0.91351058, 0.98161038]],

       [[0.99050096, 0.33771706, 0.10296923]],

       [[0.52875277, 0.21444518, 0.56029093]],

       [[0.61649283, 0.76810417, 0.7931167 ]],

       [[0.93280321, 0.95614996, 0.69655504]],

       [[0.42648707, 0.14864547, 0.73972153]],

       [[0.89650208, 0.33920012, 0.34243814]],

       [[0.36429289, 0.48547314, 0.32288754]],

       [[0.52894747, 0.96892795, 0.40189547]],

       [[0.38585824, 0.98663392, 0.03658429]],

       [[0.28541875, 0.42807598, 0.83852529]],

       [[0.84507424, 0.80321834, 0.1910805 ]],

       [[0.7829554 , 0.44673027, 0.62892521]],

       [[0.88016205, 0.28998135, 0.88300585]],

       [[0.03483477, 0.62165325, 0.7803546 ]],

       [[0.94685626, 0.67904233, 0.44508832]],

       [[0.80410183, 0.92338557, 0.43847776]],

       [[0.34127937, 0.08946804, 0.76891041]],

       [[0.57772546, 0.50932402, 0.23038

In [620]:
arr1[np.newaxis, :, :]

array([[[0.28438976, 0.80191945, 0.60096253],
        [0.30043806, 0.87945317, 0.06167689],
        [0.91175818, 0.2005994 , 0.6124592 ],
        [0.54507038, 0.09427657, 0.59008444],
        [0.69969214, 0.92910422, 0.89716314],
        [0.76264085, 0.15505067, 0.45001772],
        [0.52617206, 0.07111737, 0.53687812],
        [0.05391717, 0.54198795, 0.04876326],
        [0.79199041, 0.7219674 , 0.92189381],
        [0.50984083, 0.37828202, 0.6102297 ],
        [0.55790339, 0.12481068, 0.10521064],
        [0.19187261, 0.13044772, 0.51983727],
        [0.89474213, 0.15226236, 0.57882586],
        [0.2890542 , 0.64052575, 0.97278726],
        [0.99232076, 0.756665  , 0.76301266],
        [0.31892794, 0.91712295, 0.93891909],
        [0.31064884, 0.05031779, 0.24609595],
        [0.61431742, 0.0718654 , 0.16432139],
        [0.0030388 , 0.44440181, 0.03091029],
        [0.06281769, 0.89278193, 0.44577293],
        [0.91729165, 0.48720842, 0.80884322],
        [0.93712611, 0.50042994, 0