# **Ridge Regression**

Ridge Regression is a type of linear regression that applies L2 regularization to penalize large coefficient values. <br>
In the objective function for ridge regression, the penalty term is proportional to the square of the coefficients.

J(β)=RSS+λ 
j=1
∑
p
​
 β 
j
2
​


* Ridge tries to minimize both the loss function (RSS) and the sum of the squared coefficients (
𝛽
𝑗
2
β 
j
2
​
 ).
* The L2 penalty term (
𝜆
∑
𝑗
=
1
𝑝
𝛽
𝑗
2
λ∑ 
j=1
p
​
 β 
j
2
​
 ) grows large when the coefficients 
𝛽
𝑗
β 
j
​
  take high values.
* To reduce this penalty, Ridge Regression shrinks the coefficients towards 0 but does not set them exactly to 0.

In [4]:
from sklearn.linear_model import Ridge
import numpy as np

In [2]:
x = [1,3,5,7,9]
y = [2,6,10,14,18]

In [9]:
x = np.array(x).reshape(-1,1)
y = np.array(y).reshape(-1,1)

In [8]:
x

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [10]:
y

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [12]:
ridge = Ridge()
ridge.fit(x,y)
ridge.score(x,y)

0.9994051160023796

In [13]:
ridge.predict(x)

array([[ 2.19512195],
       [ 6.09756098],
       [10.        ],
       [13.90243902],
       [17.80487805]])