In [1]:
import numpy as np

In [6]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[17,18,19]])

In [7]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21],
       [24, 26, 28]])

In [8]:
arr1 + 9

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
np.dot(arr1,arr2)

array([[ 87,  93,  99],
       [207, 222, 237],
       [327, 351, 375]])

In [10]:
np.outer(arr1,arr2)

array([[ 10,  11,  12,  13,  14,  15,  17,  18,  19],
       [ 20,  22,  24,  26,  28,  30,  34,  36,  38],
       [ 30,  33,  36,  39,  42,  45,  51,  54,  57],
       [ 40,  44,  48,  52,  56,  60,  68,  72,  76],
       [ 50,  55,  60,  65,  70,  75,  85,  90,  95],
       [ 60,  66,  72,  78,  84,  90, 102, 108, 114],
       [ 70,  77,  84,  91,  98, 105, 119, 126, 133],
       [ 80,  88,  96, 104, 112, 120, 136, 144, 152],
       [ 90,  99, 108, 117, 126, 135, 153, 162, 171]])

In [13]:
np.linalg.det(arr1)

0.0

In [15]:
np.linalg.matrix_rank(arr1)

2

In [16]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

In [17]:
np.diag(arr1)

array([1, 5, 9])

In [18]:
np.trace(arr1)

15

In [19]:
np.linalg.cond(arr1)

5.0522794445385096e+16